name: continuous-integration-foo

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on:  ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Build with Gradle!
              working-directory: .
              run: ./gradlew build -x test

            - name: Run tests
              working-directory: .
              run: ./gradlew test

    integration-test:
        runs-on: ubuntu-latest
        needs: build-and-test
        steps:
            - uses: actions/checkout@v1
            
            - name: Run Docker
              working-directory: .
              run: docker-compose up -d --build
            - uses: actions/setup-python@v1
              with:
                python-version: '3.x'
            - name: Install requirement
              run: pip3 install -U pytest && pip3 install -U requests
            - name: Pytest
              working-directory: . 
              run: pytest
            - name: Purge containers
              working-directory: .
              run: docker-compose down
