name: continuous-integration-foo

on:
  push:
    branches:
      - master

jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Setup JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Build gradel
          working-directory: .
          run: ./gradlew build -x test

        - name: Run tests
          working-directory: .
          run: ./gradelw test 

